### ISSUE TITLE
Flashing large firmware images fails

### ISSUE THREAD

**Issue by r4d10n** [maia-sdr/plutosdr-fw#3] opened 2023-02-19 17:23 UTC
Congrats on the release Dani... Maia SDR is working wonderful... Looking forward to more features!

I tried to reinstall ADI Pluto firmware after trying Maia SDR, without luck by copying the pluto.frm to Mass Storage Disk (and ejecting), and also with update_frm.sh. I tried this on two of my revB Plutos. 

Only method that worked was DFU, while making sure uboot-env.dfu was also dfu'ed to reinit the custom changes made with fw_setenv. 

Cheers

**Comment by daniestevez** [comment] 2023-02-19 18:06
Transferring the issue to the plutosdr-fw repository...

**Comment by daniestevez** [comment] 2023-02-19 18:09
I have just checked that I can flash the ADI firmware v0.35 using the mass storage method on a Pluto rev. B that is running the Maia SDR v0.1.1 firmware.

Can you give more details about the problem? Does the LED flash rapidly after you eject the the mass storage device? After you attempt to flash the ADI firmware, does the Pluto boot to Linux correctly? What does the motd indicate when you log in by serial or ssh (you can also `cat /etc/motd`)?

**Comment by r4d10n** [comment] 2023-02-20 03:34
I am using a custom build of ADI firmware (~26MB vs ~11MB (stock v0.35) vs 13MB (maia)), which is probably causing the problem. I tried using the stock v0.35 as you suggested and it is working fine. 

I am able to install this custom build by copying the pluto.frm to a stock v0.35 installed Pluto, but not to a maia-sdr installed Pluto. The custom build fw is uploaded [here](https://www.dropbox.com/t/TtLAWToBNaajpNWw) for your reference. 

LEDs do not flash when I copy the custom fw and eject the mass storage device, which means it is not loading the custom firmware copied to the device. When I reconnect, it shows motd for maia-sdr.

**Comment by daniestevez** [comment] 2023-02-20 17:16
I think that the problem is that your custom firmware is too large. The Maia SDR firmware only leaves around 39.2MiB of free RAM, since most of the RAM is reserved for IQ recordings.

It seems that the update firmware procedure needs at least twice the firmware size of free RAM, since `/sbin/update_frm.sh` does
```
head -c -33 ${FILE} > /opt/firmware.frm
```
and both `/opt/firmware.frm` and the original firmware file sit in a RAM filesystem. This explains why attempting to flash a 26MB image won't work.

In principle it would be possible to rework `/sbin/update_frm.sh` so that it works in-place, without duplicating the firmware file in RAM.

Note that killing the `maia-httpd` process and removing everything in the `/root` directory (which contains the `maia-httpd` binary and its assets) will increase the amount of free RAM to 44.7MiB (I'm reading these values from the "available" column of `free`), but still this doesn't seem sufficient to flash a 26MB image (I didn't test it).

**Closed as completed** 2023-02-20 17:58 UTC
