### ISSUE TITLE
reset pluto to factory not working

### ISSUE THREAD

**Issue by fpgasdr** [maia-sdr/plutosdr-fw#12] opened 2024-10-15 08:51 UTC
Hello Daniel,
since mi pluto is experience an anomalous behavior(disconnects after 10 seconds in every OS I connect to) I want to reset to factory default but the typical mode of store the fw in the mass storage is not working since in I'm 10 seconds I'm able to store the firmware and unmount the disk but nothing happens, no led blinking fast.

Also since I only have 10 seconds to make anything I'm i little bit precarious with my hardware.

What I could do?

**Comment by fpgasdr** [comment] 2024-10-15 08:52
also tried to update with newer maia fw but it says there is not enough  space...

**Comment by daniestevez** [comment] 2024-10-15 08:54
What version of Maia SDR do you have installed in the Pluto?

**Comment by fpgasdr** [comment] 2024-10-15 09:26
hello Daniel,

it's an older since discover your project in fosdem talk (maia-sdr-v0.4.2).

also I remember I tried to use a android tablet with it without success (change the ip address and ethernet mode).

thanks

**Comment by daniestevez** [comment] 2024-10-15 11:41
Some comments:

* Replacing the Maia SDR Pluto firmware v0.4.2 by the ADI default firmware using the `pluto.frm` file with the USB mass storage device should work fine. The issue related to firmware updates only affected installing a Maia SDR firmware >=v0.5.0 when running a Maia SDR firmware <v0.5.0. Any other combination (and in particular reverting to the default firmware) should work.
* I'd say that it takes more than 10 seconds to write the firmware image to the QSPI, so if you're having an issue that makes the Pluto crash in 10 seconds, you might get a partially flashed image if you try to flash it.
* If you want to install the ADI default firmware and are having troubles, I suggest you try to [use DFU mode to flash it](https://wiki.analog.com/university/tools/pluto/users/firmware#dfu_update).
* Your problem looks like a hardware problem, so I wouldn't be surprised if flashing a different firmware image doesn't fix it.

**Comment by fpgasdr** [comment] 2024-10-15 14:05
thanks daniel,

the pluto.frm solved my issue.

I guess when tried to connect the android phone to plutosdr I messed with some configuration with the Ethernet connection.

If I want to use a newer Maia version I can have problems with getting back to analog firmware?

regards,
Julian.

**Comment by daniestevez** [comment] 2024-10-15 14:08
> If I want to use a newer Maia version I can have problems with getting back to analog firmware?

No. Getting back to the ADI default firmware is always supported.

**Comment by daniestevez** [comment] 2024-10-16 11:24
Closing this issue, since the problem is solved.

**Closed as completed by daniestevez** 2024-10-16 11:24 UTC
